### ISSUE TITLE
question: should we rename this repo *Kalligator*

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/kali_dumps_scripts#5]
\from @adipasquale 

This project is expending from a basic scraper to a *data eating monster*.
We need a new name for it before it's to late :)

What do you thing about naming it : **Kalligator**

---

Saw that cool pic under the *kalligator* twitter hash tag yesterday night...

![biq9llacyaa2tyk](https://user-images.githubusercontent.com/730511/51591179-973d4180-1eec-11e9-8c44-38341532dd49.jpg)

**Comment by adipasquale** [comment]
haha I was thinking about `kalimator` or `kalirama`, but `kaligator` is way better. I would spell it with a single `l` though, to respect the LEGI database name

I still don't exactly know what this repository will evolve to, so I think it's fine if we have a not so explicit name yet.

**Comment by adipasquale** [comment]
we won't have the instagram account though ^^ https://www.instagram.com/kaligator/

**Comment by lionelB** [comment]
superkalifragilistic

**Comment by douglasduteil** [comment]
\from @adipasquale
Renamed **kaligator**

**Comment by lionelB** [comment]
😭

**Comment by adipasquale** [comment]
haha, don't worry @lionelB I'll have at least another project on KALI I'm keeping superkalifragilistic in memory :)
